##--------------------------------------------------------------------
## rmqtt-acl
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/acl.md

#Disconnect if publishing is rejected
disconnect_if_pub_rejected = true

rules = [
    ["deny", "all", "subscribe", ["test/nosubscribe"]],
    ["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
    ["allow", { ipaddr = "127.0.0.1" }, "pubsub", ["$SYS/#", "#"]],
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],
#    ["allow", "all"]
    ["deny", "all"]
]

