##--------------------------------------------------------------------
## rmqtt-http-api
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/http-api.md

## Max Row Limit
max_row_limit = 10_000
## HTTP Listener address
http_laddr = "0.0.0.0:6060"
## Indicates whether to print HTTP request logs
http_request_log = false

##Message expiration time, 0 means no expiration
message_expiry_interval = "5m"

## Prometheus metrics data caching interval.
##
## Value: Duration
## Default: "5s"
prometheus_metrics_cache_interval = "5s"

