##--------------------------------------------------------------------
## rmqtt-bridge-egress-kafka
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/bridge-egress-kafka.md

[[bridges]]
# Whether to enable
enable = true
# Bridge name
name = "bridge_kafka_1"

# The list of broker (server) addresses for the Kafka cluster.
#servers = "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094"
servers = "127.0.0.1:9092"
# client.id
client_id_prefix = "kafka_001"

# Maximum limit of clients connected to the remote kafka broker
concurrent_client_limit = 3

# See more properties and their definitions at https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
[bridges.properties]
"message.timeout.ms" = "5000"

[[bridges.entries]]
#Local topic filter: All messages matching this topic filter will be forwarded.
local.topic_filter = "local/topic1/egress/#"

remote.topic = "remote-topic1-egress-${local.topic}"
#The queue_timeout parameter controls how long to retry for if the librdkafka producer queue is full. 0 to never block.
remote.queue_timeout = "0m"
#Sets the destination partition of the record.
#remote.partition = 0

# Number of leading topic levels to skip when substituting ${local.topic} in `remote.topic`.
# For example, if the local topic is `a/b/c/d` and skip_local_topic_levels = 2,
# ${local.topic} will resolve to `c/d`.
#remote.skip_levels = 0

[[bridges.entries]]
#Local topic filter: All messages matching this topic filter will be forwarded.
local.topic_filter = "local/topic2/egress/#"

remote.topic = "remote-topic2-egress"
#remote.queue_timeout = "0m"
#remote.partition = 0

