[package]
name = "rmqtt-web-hook"
version = "0.1.2"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt = "0.3"
serde = { version = "1.0", features = ["derive"] }
backoff = { version = "0.4", features = ["futures", "tokio"] }