[package]
name = "rmqtt-web-hook"
version = "0.1.2"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt.workspace = true
serde = { workspace = true, features = ["derive"] }
backoff = { version = "0.4", features = ["futures", "tokio"] }