[package]
name = "rmqtt-message-storage"
version = "0.1.1"
description = "Published messages are stored until expiration and forwarded to new matching subscriptions. Theyâ€™re cleared automatically after expiring."
repository = "https://github.com/rmqtt/rmqtt/tree/master/rmqtt-plugins/rmqtt-message-storage"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmqtt = { workspace = true, features = ["plugin", "msgstore", "retain"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync", "time"] }
rmqtt-storage = { version = "0.6", default-features = false, features = ["ttl"]}
#rmqtt-storage = { path = "../../../rmqtt-storage", default-features = false, features = ["ttl"]}
rust-box.workspace = true
futures.workspace = true
futures-time.workspace = true
async-trait.workspace = true
log.workspace = true
serde_json.workspace = true
anyhow.workspace = true
once_cell.workspace = true
get-size.workspace = true
scc.workspace = true

[dev-dependencies]
bytes.workspace = true


