[package]
name = "rmqtt-message-storage"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true


[dependencies]
rmqtt.workspace = true
rmqtt-macros.workspace = true
serde = { workspace = true, features = ["derive"] }
rmqtt-storage = { version = "0.5.1", default-features = false, features = ["ttl"]}
#rmqtt-storage = { path = "../../../rmqtt-storage", default-features = false, features = ["ttl"]}
futures-time = "3.0.0"